name: MinGW build 2

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: pdf4qt

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          dir: '${{ github.workspace }}/qt/'
          install-deps: 'true'
          modules: 'qtspeech qtmultimedia'

      - name: 'VCPKG: Set up VCPKG'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics
          .\vcpkg integrate install
          set VCPKG_ROOT=${env:GITHUB_WORKSPACE}\vcpkg\
          set "VCPKG_BINARY_SOURCES=clear;files,${env:GITHUB_WORKSPACE}\vcpkg\archives,readwrite"

      - name: 'VCPKG: Cache vcpkg dependencies'
        uses: actions/cache@v4
        with:
          path: |
            ./vcpkg/downloads
            ./vcpkg/packages
            ./vcpkg/installed
            ./vcpkg/archives
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}


      - name: 'VCPKG: Install project dependencies'
        run: |
          .\vcpkg install tbb openssl lcms zlib openjpeg freetype ijg-libjpeg libpng blend2d --triplet x64-mingw-dynamic
        working-directory: vcpkg

      - name: Build project
        working-directory: pdf4qt
        shell: pwsh
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_VCPKG_BUILD_TYPE=Release -DPDF4QT_INSTALL_QT_DEPENDENCIES=ON -DPDF4QT_INSTALL_DEPENDENCIES=ON -DCMAKE_TOOLCHAIN_FILE="${env:GITHUB_WORKSPACE}\vcpkg\scripts\buildsystems\vcpkg.cmake" -DPDF4QT_QT_ROOT="${env:Qt6_DIR}" -DPDF4QT_INSTALL_MSVC_REDISTRIBUTABLE=ON -DPDF4QT_INSTALL_PREPARE_WIX_INSTALLER=ON -DPDF4QT_INSTALL_TO_USR=ON -DCMAKE_CXX_COMPILER:FILEPATH=D:/a/PDF4QT/PDF4QT/qt/Qt/Tools/mingw1310_64/bin/g++.exe -DCMAKE_GENERATOR:STRING=Ninja -DVCPKG_TARGET_TRIPLET:STRING=x64-mingw-dynamic -DCMAKE_C_COMPILER:FILEPATH=D:/a/PDF4QT/PDF4QT/qt/Qt/Tools/mingw1310_64/bin/gcc.exe
          cmake --build build --config Release -j6
          cmake --install build

      - name: Upload Windows package
        uses: actions/upload-artifact@v4
        with:
          name: 'pdf4qt-${{ runner.os }}.zip'
          path: .\pdf4qt\build\install\usr\bin
          retention-days: 30
